name: Deploy to AKS Cluster
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: angularapp.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build . -t angularapp.azurecr.io/frontend:${{ github.sha }}
        docker push angularapp.azurecr.io/frontend:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: pixelCluster
        resource-group: gr-pixel-containers
        
    # Create Secret manually in ingress-basic namespace
    - run: |
        kubectl create secret docker-registry k8s-secret-front \
          --docker-server=angularapp.azurecr.io \
          --docker-username=${{ secrets.ACR_USERNAME }} \
          --docker-password=${{ secrets.ACR_PASSWORD }} \
          --namespace=ingress-basic


    - name: Update deployment image
      run: |
        sed -i 's|<IMAGE_PLACEHOLDER>|angularapp.azurecr.io/frontend:${{ github.sha }}|' k8s/deployment.yaml
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        images: |
          angularapp.azurecr.io/frontend:${{ github.sha }}
        imagepullsecrets: |
          k8s-secret-front
        namespace: ingress-basic